language: python
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq curl
after_script:
 - bash -c \"$(curl -fsSL https://raw.githubusercontent.com/MaT1g3R/travis_discord/master/travis.sh)\"
